# The New Economy v0.1.2.0
# Author: creatorfromhell
# License: https://github.com/TheNewEconomy/EconomyCore/blob/main/license.md
Core:

  config-version: 3

  #Cracked Server? Set this to true. May cause data issues as spigot/paper UUIDs are unpredictable.
  #Do not change this unless you know what you're doing.
  Offline: false

  #Configurations relating to debugging
  Debugging:

    #The mode that debug should be in.
    #Modes: Off, Standard, Detailed, Developer
    Mode: "Off"

  #All configurations relating to regions/worlds.
  Region:

    #The region mode that TNE should be using for separating balances.
    #Valid modes: world, biome
    Mode: "world"

    #Should TNE separate account balances by region?
    #This will separate them based on the Mode configuration.
    MultiRegion: false

    #The name of the region to use if MultiRegion is set to false.
    #Setting to TNE_SYSTEM will let TNE decide the default region.
    DefaultRegion: "TNE_SYSTEM"

    #Should TNE automatically group the world's realms with the main overworld world.
    #Example: Setting this to true would make world, world_nether and world_the_end share balances automatically.
    GroupRealms: true

    #Regions that should have their economy disabled.
    DisabledRegions:
      - ExampleWorld

    #Regions that should have their economy disabled.
    SharedRegions:

      ExampleRegion: test

  #All configurations relating to the server in general.
  Server:

    #The geyser prefix for the server.
    Geyser: "."

    #Whether the ServerID config should be random on each startup. This could impact syncing on
    #restarts, but will not impact anything significant.
    RandomUUID: false

    #Whether to import exist item currencies into a player's balance when they join for the first time.
    ImportItems: true

    #Should TNE disable mob drops that are valid item currencies?
    MobDrop: true

    #Should experience gaining be disabled? This will help for servers that use Experience as currency.
    ExperienceGain: false

    #The name of this server for data-related purposes. Max length is 100 characters.
    Name: "Main Server"

    #All configurations relating to the server's economy account.
    Account:

      #Enable the server account?
      Enabled: true

      #The name of the server account. Max length is 100 characters.
      Name: "Server_Account"

      #The starting balance for the server account.
      Balance: 500

  #All configurations relating to TNE commands
  Commands:

    #Configuration if money action commands, such as give/take/set require individual permissions.
    LimitCurrency: false

    #Configurations relating to balance commands.
    Balance:

      #Should the /money balance command be restricted to one currency?
      Restrict: false

      #If restrict is true, only print balances for the following currency. If it can't find a currency
      #based on the following identifier, it'll use the region default
      Currency: "USD"

    #Configurations relating to the money top command.
    Top:

      #Should balances in /baltop be formatted?
      Format: true

      #How often should the data used for /baltop be refreshed?
      #This is in seconds.
      Refresh: 1200

      #A list of values to use to exclude certain users from baltop if the username contains these values.
      Exclusions:
      - "^town-.*"
      - "^nation-.*"
      - "^faction-.*"
      - "^towny-.*"

    #Extra configurations regarding the pay command
    Pay:

      #Can players use /pay on offline players?
      Offline: true

      #How close to another player someone must be, in blocks, in order to use /pay on them. Set to 0 to disable.
      Radius: 0
  
  #All configurations relating to update checking
  Update:
  
    #Should TNE check for updates?
    Check: true
    
    #Should TNE notify any users with the tne.admin node of TNE updates on join?
    Notify: true

  #All configurations relating to the transaction system.
  Transactions:

    #The time format to use when displaying transaction history data.
    Format: "M, d y"

    #The timezone to use for transactions.
    Timezone: "US/Eastern"

    #Configurations relating to tracking large transactions
    Tracking:

      #If large transaction tracking is enabled or not.
      Enabled: true

      #The threshold to mark a transaction for tracking.
      Amount: "400"

    #Configurations relating to Transaction History
    History:

      #How often should the data used for /transaction list be refreshed?
      #This is in seconds.
      Refresh: 1200

    #Configurations relating to conversion transactions.
    Conversion:

      #Tax-related configurations.
      Tax:

        #If this tax is enabled.
        Enabled: false

        #The tax to apply to a conversion transaction.
        #The tax may also be a percentage. For percent follow number by the % symbol, i.e 10%
        Rate: 0.0

    #Configurations relating to desposit transactions.
    Deposit:

      #Tax-related configurations.
      Tax:

        #If this tax is enabled.
        Enabled: false

        #The tax to apply to a deposit transaction.
        #The tax may also be a percentage. For percent follow number by the % symbol, i.e 10%
        Rate: 0.0

    #Configurations relating to pay transactions.
    Pay:

      #Tax-related configurations.
      Tax:

        #If this tax is enabled.
        Enabled: false

        #The tax to apply to the sender
        #The tax may also be a percentage. For percent follow number by the % symbol, i.e 10%
        Sender: 0.0

        #The tax to apply to the receiver
        #The tax may also be a percentage. For percent follow number by the % symbol, i.e 10%
        Receiver: 0.0

    #Configurations relating to withdraw transactions.
    Withdraw:

      #Tax-related configurations.
      Tax:

        #If this tax is enabled.
        Enabled: false

        #The tax to apply to a withdrawal transaction.
        #The tax may also be a percentage. For percent follow number by the % symbol, i.e 10%
        Rate: 0.0