name: TheNewEconomy
version: 0.1.3.0
description: The original feature-packed economy plugin for Minecraft.
author: creatorfromhell
main: net.tnemc.paper.TNE
api-version: '1.19'

load: POSTWORLD

dependencies:
  - name: Towny
    required: false
    bootstrap: false
  - name: Multiverse-Core
    required: false
    bootstrap: false
  - name: LuckPerms
    required: false
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: true
  - name: Treasury
    required: false
    bootstrap: false
  - name: mcMMO
    required: false
    bootstrap: false
  - name: Essentials
    required: false
    bootstrap: false
  - name: EssentialsX
    required: false
    bootstrap: false
  - name: PlaceholderAPI
    required: false
    bootstrap: true