name: TheNewEconomy
version: 0.1.2.0
description: The original feature-packed economy plugin for Minecraft.
author: creatorfromhell
main: net.tnemc.paper.TNE
api-version: '1.13'
dependencies:
  - name: Towny
    required: false
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: false
  - name: mcMMO
    reqiuired: false
    bootstrap: false
  - name: Essentials
    reqiuired: false
    bootstrap: false
  - name: PlaceholderAPI
    reqiuired: false
    bootstrap: false

load-before:
  - name: Towny
    bootstrap: false