name: TheNewEconomy
version: 0.1.3.2
description: The original feature-packed economy plugin for Minecraft.
author: creatorfromhell
main: net.tnemc.folia.TNE
api-version: '1.19'

#Has to be included for folia support
folia-supported: true

load: POSTWORLD

dependencies:
  - name: Towny
    required: false
  - name: Multiverse-Core
    required: false
  - name: LuckPerms
    required: false
  - name: Vault
    load: BEFORE
    required: false
  - name: Treasury
    load: BEFORE
    required: false
  - name: mcMMO
    required: false
  - name: Essentials
    required: false
  - name: EssentialsX
    required: false
  - name: PlaceholderAPI
    load: BEFORE
    required: false
    join-classpath: true